# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SolarPWCalculator
                                 A QGIS plugin
 pass
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-10-07
        copyright            : (C) 2022 by SABZ
        email                : yavuzdogan@gumushane.edu.tr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SolarPWCalculator class from file SolarPWCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Solar_PW_Calculator import SolarPWCalculator
    return SolarPWCalculator(iface)
